class Mnemonics:
    NOP = "NOP"
    MOV = "MOV"
    PUSH = "PUSH"
    POP = "POP"
    JMP = "JMP"
    CMP = "CMP"
    ADD = "ADD"
    MUL = "MUL"
    SUB = "SUB"
    DIV = "DIV"
    DMP = "DMP"
    JNE = "JNE"
    JE = "JE"

    SYS_WRITE = "SYS_WRITE"